package eu.telecom_bretagne.ambSocialNetwork.front.vaadin;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.RichTextArea;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TextArea;

public class TestComposite extends CustomComponent
{

  /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

  @AutoGenerated
  private AbsoluteLayout mainLayout;
  @AutoGenerated
  private TabSheet tabSheet_1;
  @AutoGenerated
  private RichTextArea richTextArea_1;
  @AutoGenerated
  private TextArea textArea_1;
  /**
   * The constructor should first build the main layout, set the
   * composition root and then do any custom initialization.
   *
   * The constructor will not be automatically regenerated by the
   * visual editor.
   */
  public TestComposite()
  {
    buildMainLayout();
    setCompositionRoot(mainLayout);

    // TODO add user code here
  }

  @AutoGenerated
  private AbsoluteLayout buildMainLayout()
  {
    // common part: create layout
    mainLayout = new AbsoluteLayout();
    mainLayout.setImmediate(true);
    mainLayout.setWidth("100%");
    mainLayout.setHeight("100%");
    
    // top-level component properties
    setWidth("100.0%");
    setHeight("100.0%");
    
    // tabSheet_1
    tabSheet_1 = buildTabSheet_1();
    mainLayout.addComponent(tabSheet_1, "top:20.0px;left:20.0px;");
    
    return mainLayout;
  }

  @AutoGenerated
  private TabSheet buildTabSheet_1()
  {
    // common part: create layout
    tabSheet_1 = new TabSheet();
    tabSheet_1.setImmediate(true);
    tabSheet_1.setWidth("780px");
    tabSheet_1.setHeight("59.2%");
    
    // textArea_1
    textArea_1 = new TextArea();
    textArea_1.setImmediate(false);
    textArea_1.setWidth("100.0%");
    textArea_1.setHeight("100.0%");
    tabSheet_1.addTab(textArea_1, "HTML", null);
    
    // richTextArea_1
    richTextArea_1 = new RichTextArea();
    richTextArea_1.setImmediate(false);
    richTextArea_1.setWidth("100.0%");
    richTextArea_1.setHeight("100.0%");
    tabSheet_1.addTab(richTextArea_1, "WISIWYG", null);
    
    return tabSheet_1;
  }

}
